# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       fheroes2

# >> macros
# << macros

Summary:    Recreation of the Heroes of Might and Magic II game engine.
Version:    1.0.4.1
Release:    1
Group:      Amusements/Games
License:    LICENSE
URL:        https://github.com/Kormil/fheroes2
Source0:    %{name}-%{version}.tar.bz2
Source100:  fheroes2.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   zlib
Requires:   libpng
Requires:   SDL2
Requires:   SDL2_mixer
Requires:   SDL2_image
Requires:   SDL2_ttf
Requires:   SDL2_gfx
Requires:   wayland
Requires:   wayland-egl
Requires:   boost-filesystem
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  pkgconfig(libpng)
BuildRequires:  pkgconfig(sdl2)
BuildRequires:  pkgconfig(SDL2_image)
BuildRequires:  pkgconfig(SDL2_mixer)
BuildRequires:  pkgconfig(SDL2_ttf)
BuildRequires:  pkgconfig(SDL2_gfx)
BuildRequires:  pkgconfig(wayland-client)
BuildRequires:  gettext
BuildRequires:  boost-devel
BuildRequires:  boost-filesystem
BuildRequires:  desktop-file-utils
BuildRequires:  cmake

%description
FHeroes2 recreation of the Heroes of Might and Magic II game engine.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake . 
make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
